ALTER TABLE "Artist"
ADD COLUMN "dashboardCoverZoom" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN "dashboardCoverPositionX" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN "dashboardCoverPositionY" INTEGER NOT NULL DEFAULT 50;